config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  resources :users, except: :index
  resources :videos do
    resources :descriptions, except: [:index, :show]
  end


  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get 'logout' => 'sessions#destroy'
  get 'search' => "videos#search"
end

app/models/description.rb
class Description < ActiveRecord::Base
  belongs_to :writer, class_name: "User", foreign_key: "writer_id"
  belongs_to :video

  validates :content, presence: true
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :uploads, class_name: "Video", foreign_key: "uploader_id"
  has_many :descriptions, foreign_key: "writer_id"
  has_many :notifications

  validates :username, uniqueness: true,
    presence: true
  validates :email, uniqueness: true,
    presence: true,
    format: { with: /\w+@\w+\.\w{2,3}/i, message: "please enter a valid email address" }
    validates :password, presence: true
    has_secure_password
end

app/models/video.rb
class Video < ActiveRecord::Base
  include PgSearch
  belongs_to :uploader, class_name: "User", foreign_key: "uploader_id"
  has_one :description

  validates :url, presence: true
  validates :embed_code, presence: true
  validates :title, presence: true
  validates :thumbnail, presence: true

  pg_search_scope :search_by_title, :against => :title

  def get_video_info
    video_info = VideoInfo.new(self.url)
    unless video_info.available?
      raise RuntimeError, "The url you entered was not valid. Please ry again"
    else
      self.embed_code = video_info.embed_code
      self.title = video_info.title
      self.thumbnail = video_info.thumbnail_medium
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/descriptions_controller.rb
class DescriptionsController < ApplicationController
  before_action :set_description, only: [:show, :edit, :update, :destroy]

  def new
    @description = Description.new
    @video = Video.find(params[:video_id])
  end

  def create
    current_user = User.find(session[:user_id])
    @video = Video.find(params[:video_id])
    @description = Description.new(description_params)
    if @description.save
      current_user.descriptions << @description
      @video.description = @description
      redirect_to @video
    else
      render video
    end
  end

  def edit
  end

  def update
    @video = Video.find(params[:video_id])
    if @description.update(description_params)
      redirect_to @video
    else
      render @video
    end
  end

  def destroy
    @video = Video.find(params[:video_id])
    @description.destroy
    redirect_to @video
  end

  private

  def set_description
    @description = Description.find(params[:id])
  end

  def description_params
    params.require(:description).permit(:content, :rating)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if logged_in?
      redirect_to current_user
    end
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
    session[:user_id] = @user.id
    redirect_to @user
    else
      flash[:danger] = "Login information not found"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    render 'new'
  end

  private
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    session[:user_id] ? true : false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
    @videos = nil
    if @user.uploads.any?
      @videos = @user.uploads
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: "User was successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  def index
    @videos = Video.includes(:description).where(description = nil).paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @video = Video.new
    if session[:user_id] == nil
      redirect_to login_path
    end
  end

  def search
    search = params[:search]
    @videos = Video.search_by_title(search).paginate(:page => params[:page], :per_page => 10)
    render :index
  end

  def create
    current_user = User.find(session[:user_id])
    @video = Video.new(video_params)
    video_info = VideoInfo.new(@video.url)
    @video.embed_code = video_info.embed_code
    @video.title = video_info.title
    @video.thumbnail = video_info.thumbnail_medium
    if @video.save && video_info.available?
      current_user.uploads << @video
      redirect_to current_user
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @video.update(video_params)
      redirect_to @video
    else
      render :edit
    end
  end

  def destroy
    @video.destroy
  end

  private

  def set_video
    @video = Video.find(params[:id])
  end

  def video_params
    params.require(:video).permit(:url, :description, :title, :embed_code, :thumbnail)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    session[:user_id] ? true : false
  end
end

app/views/descriptions/new.html.erb
<%= link_to "Back", @video_path %>
<p><b>Write a Description</b></p>
<p><%= @video.title %></p>
<p><%=raw @video.embed_code %></p>
<p><%= @video.comment %></p>
<%= form_for [@video, @description] do |f| %>
  <div class="field">
    <%= f.label "Description" %><br>
    <%= f.text_area :content %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Writeviewer</title>
  <%= stylesheet_link_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
  <strong id="title" alt="Link to Homepage"><%= link_to "WriteViewer", root_path %></strong>
  <nav>
    <p>Navigation</p>
    <% if current_user && logged_in? %>
      Welcome <%= current_user.username%>
      <%= link_to "Log Out", logout_path, method: :delete %>
      <%= link_to "Upload a Video", new_video_path %>
    <% else %>
      <%=link_to "Log In", login_path %>
      <%=link_to "Register", new_user_path %>
    <% end %>
    <%= link_to "Uploaded Videos", videos_path %>
    <%= form_tag search_path, :method => 'get' do %>
      <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil %>
      </p>
    <% end %>
  </nav>

  <%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User Information</h1>
<%= render "form" %>

<%= link_to 'Back', @user %>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<p><strong>Username: </strong><%= @user.username %></p>
<p><strong>Email: </strong><%= @user.email %></p>
<div>
  <% if @videos %>
    <% @videos.each do |video| %>
      <p><%=link_to video.title, video %></p>
      <% if video.description %>
        <p>This video has been described</p>
      <% end %>
    <% end %>
  <% else %>
    <strong>You haven't uploaded any videos!</strong>
  <% end %>
</div>

app/views/videos/index.html.erb
<% @videos.each do |video| %>

  <p><%= link_to video.title, video %></p>
  <img src=<%= video.thumbnail %>>
  <p>Described:
    <% if video.description %>
      <strong>Yes</strong>
    <% else %>
      <strong>No</strong>
    <% end %>
  </p>
<% end %>
<p><%= will_paginate @videos %></p>

app/views/videos/new.html.erb
<h1>New Video</h1>
<%= form_for(@video) do |f| %>
  <div class="field">
    <%= f.label "Video URL" %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label "(Optional) Instructions" %><br>
    <%= f.text_field :comment %>
  </div>
  <div>
    <%= f.submit "Submit"  %>
  </div>
<% end %>

app/views/videos/show.html.erb
<strong><%= @video.title %></strong>
<p>Uploaded by <%=@video.uploader.username%>, <%=@video.created_at.strftime("%F")%></p>
<p><%=raw @video.embed_code %></p>
<p><%= @video.comment %></p>
<% unless @video.description %>
  <div>
    <% if logged_in? %>
      <%= link_to "Write a description", new_video_description_path(@video) %>
    <% else %>
      <%= link_to "Want to describe it? Log In here.", login_path %>
    <% end %>
  </div>
<% else %>
  <div>
    <%= @video.description.content %>
  </div>
  <% if @video.uploader == current_user && @video.description.rating == nil %>
    <p>Was this description helpful?</p>
    <%= button_to "No, delete it", [@video, @video.description], :method => :delete %>
  <% end %>
<% end %>